In [2]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                        [-1.5, 2.4, 3.5],
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [3]:
sample_data.shape

(4, 3)

Teknik Binarisation

In [4]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [10]:
# parameter yang digunakan untuk ambang batas
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

Teknik Scalling

In [11]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [13]:
# Scalling Min Max Scaller
preprocessor = preprocessing.MinMaxScaler(feature_range=(0,0.1))
preprocessor.fit(sample_data)

#Cara 1
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.04864865, 0.05825243, 0.09912281],
       [0.        , 0.1       , 0.08157895],
       [0.02702703, 0.        , 0.1       ],
       [0.1       , 0.09902913, 0.        ]])

In [14]:
#Cara 2
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.04864865, 0.05825243, 0.09912281],
       [0.        , 0.1       , 0.08157895],
       [0.02702703, 0.        , 0.1       ],
       [0.1       , 0.09902913, 0.        ]])

Teknik Normalization L1

In [15]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [22]:
l1_normalizer = preprocessing.Normalizer(norm='l1')
l1_normalized_data = l1_normalizer.fit_transform(sample_data)
l1_normalized_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

Teknik Normalization L2

In [23]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [24]:
l1_normalizer = preprocessing.Normalizer(norm='l2')
l1_normalized_data = l1_normalizer.fit_transform(sample_data)
l1_normalized_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

Encoding

In [25]:
label_kategori = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu']
encoder = preprocessing.LabelEncoder()
encoder.fit(label_kategori)

print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '=', i)


Label mapping:
jumat = 0
kamis = 1
minggu = 2
rabu = 3
sabtu = 4
selasa = 5
senin = 6


Latihan Training set dan Test set

In [31]:
from sklearn.model_selection import train_test_split

X_data = range(10)
y_data = range(10)

print("Random State ditentukan")
for i in range(3):
    X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.3, random_state=42)
    print(y_test)

print("Random State tidak ditentukan")
for i in range(3):
    X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.3, random_state=None)
    print(y_test)

Random State ditentukan
[8, 1, 5]
[8, 1, 5]
[8, 1, 5]
Random State tidak ditentukan
[6, 8, 3]
[1, 7, 2]
[4, 7, 8]


Latihan SKLearn Train Test Split

In [32]:
import sklearn
from sklearn import datasets

iris = datasets.load_iris()

In [33]:
x=iris.data
y=iris.target

In [34]:
from sklearn.model_selection import train_test_split

# membagi dataset menjadi training dan testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [35]:
len(x_test)

30

Latihan Cross Validation

In [36]:
import sklearn
from sklearn import datasets

#Load iris dataset
iris = datasets.load_iris()

In [37]:
# mendefinisikan atribut dan label pada dataset
x=iris.data
y=iris.target

In [38]:
from sklearn import tree

# membuat model dengan decision tree classifier
clf = tree.DecisionTreeClassifier()

In [39]:
from sklearn.model_selection import cross_val_score

# mengevaluasi performa model dengan cross_val_score
scores = cross_val_score(clf, x, y, cv=5)

In [40]:
scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])